<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KokoroSharp.CPU" Version="0.8.4" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
